import type { Metadata } from "next"
import "./globals.css"
import RebondGrotesque from "@/lib/fonts"
import {
	ClerkProvider,
} from '@clerk/nextjs'

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body
					className={`${RebondGrotesque.className} antialiased bg-background text-text`}
				>
					{/* <header className="flex justify-end items-center p-4 gap-4 h-16">
						<SignedOut>
							<SignInButton />
							<SignUpButton />
						</SignedOut>
						<SignedIn>
							<UserButton />
						</SignedIn>
					</header> */}
					{children}
				</body>
			</html>
		</ClerkProvider>
	)
}
